version: '3'
services:
  vnstat-dashboard:
    build: .
    container_name: vnstat-dashboard
    network_mode: "host"
    volumes:
          - /var/lib/vnstat:/var/lib/vnstat
          - /usr/bin/vnstat:/usr/local/bin/vnstat
          - /etc/localtime:/etc/localtime:ro
          - /var/run/docker.sock:/var/run/docker.sock
